### ISSUE TITLE
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.

### ISSUE THREAD

**Issue by KasperH2** [liaoherui/VirStrain#1]
Hi, very interesting program.
I tried using it to build my own reference data base using:
python VirStrain_build.py -i <MSA.fasta> --o <out_dir>
but I am getting an error:

```
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Use of uninitialized value $char in pattern match (m//) at bin/aln2cluster-overlap-kmer-withd.pl line 80.
Progress:  1 / 14
Progress:  2 / 14
Progress:  3 / 14
Progress:  4 / 14
Progress:  5 / 14
Progress:  6 / 14
Progress:  7 / 14
Progress:  8 / 14
Progress:  9 / 14
Progress:  10 / 14
Progress:  11 / 14
Progress:  12 / 14
Progress:  13 / 14
Progress:  14 / 14
Kmer POS-Snp file done! Start generating matrix.
rm: cannot remove 'Vbuild_tem.column': No such file or directory
rm: cannot remove 'Vbuild_tem_cls.aln': No such file or directory
```
There is 15 references in the multiple sequence alignment, so it could seem that something is wrong with them, but I generated them with MAFFT and they look very standard e.g.:

>\>Reference1
ATCGATCGA
>\>Reference2
ATCGATCAA

I have the exact requirement versions that you recommend. 
It seems that I can still use the database with the VirStrain.py, but I wonder if the program runs correctly, because of the error messages shown?  
Do you have an idea of the problem? 
Also a quick side question: Is there any implications in using your program for DNA viruses compared to RNA viruses?
Thank you very much.

**Comment by liaoherui** [comment]
Hi, thanks for using VirStrain.

The message "Use of uninitialized value $char......" is just the warning information output by Perl script, not an error. This is normal and has no influence on the result.  If you can use the database with the VirStrain.py, it means the database is constructed correctly. 

For DNA viruses, in theory, VirStrain should work. But I am not very sure cause I haven't done experiments on DNA viruses. 

If you still have problems with using VirStrain, feel free to ask problems!

**Comment by KasperH2** [comment]
Thanks for the quick reply! Alright, I think it is working then, but actually in the Ops_ps_depth.csv output file, there is no information other than this one line:
```
ID,Column_ID,None,None
```
Isn't there supposed to be some data below these column headers?
Also, from the VirStrain_report.txt file the output shows 10 SNV positions:
``` 
{'82-A': 18038, '108-T': 24726, '130-A': 5387, '144-G': 6259, '432-G': 3802, '531-A': 15795, '646-A': 402, '920-T': 10724, '1134-T': 6466}
```
These are all between positions 82 to 1334, while the genomes are about 7900bp long. I wonder if there is some cap on the amount of the SNV's chosen and if it only chooses the first 10 it finds? 
I know that the program is supposed to find the "most important" SNV's but it's just a bit strange that they all lie in the range of 0-1334. Or is it actually using 14 SNV? It could seem so in the below. Still seems strange.  
```
>>Highest_Map_Strains (Could be FP):
>>Top10_Score_Strains:
		>K02718.1	Cluster1_1	NA	1.0	9/14	9/14	NA	NA
		>HQ644236.1	Cluster8_1	NA	1.0	9/14	9/14	NA	NA
		>AF534061.1	Cluster4_1	Not_record	0.9956113058002816	8/14	8/14	NA	NA
		>AF536179.1	Cluster5_1	Not_record	0.9411893142938241	8/14	8/14	NA	NA
		>KU053931.1	Cluster15_1	Not_record	0.9316695597113505	8/14	8/14	NA	NA
		>KU053914.1	Cluster11_1	Not_record	0.8728588740051748	7/14	7/14	NA	NA
		>KU053915.1	Cluster12_1	Not_record	0.8728588740051748	7/14	7/14	NA	NA
		>HQ644298.1	Cluster10_1	Not_record	0.8684701798054564	6/14	6/14	NA	NA
		>HQ644257.1	Cluster9_1	Not_record	0.814594045786526	7/14	7/14	NA	NA
		>KU053920.1	Cluster13_1	Not_record	0.814594045786526	7/14	7/14	NA	NA
```
To clarify, here is an overview of the data aligned with BWA-mem and shown in IGV from position 0-7904:
![image](https://user-images.githubusercontent.com/45485501/120171428-54997b80-c202-11eb-9684-636df3f0bc01.png)
The bottom window is the aligned reads. The top window shows SNVs in the strains relative to K02718.1. 
Should I take it as the program only finds "important" SNVs up to position 1337?
Thanks!

**Comment by liaoherui** [comment]
Hi,
 
VirStrain is designed for the fast identification of large-scale strains (>1000). When the number of strains is small, the algorithm will choose limited but most important SNV sites to distinguish these strains. In this case, only very few sites are selected. **But I will add a "manual-covering" function to make the program covers more sites when the strain number is small.** 

Will do this asap. I will let you know when I finish the new function. :) Thanks for your good question!

**Comment by liaoherui** [comment]
Hi,

The manual-covering function is updated. Now you can use it with the command below.

`python VirStrain_build.py -i <Input_MSA> -d <Database_Dir> -s 1`

Any other problems, feel free to ask!

**Comment by KasperH2** [comment]
Very cool, thank you! Will try it out later

**Comment by KasperH2** [comment]
It works! However, I get this message:
```
Traceback (most recent call last):
  File "bin/S3_Strain_pred_My_Method_For_HIV.py", line 102, in <module>
    dscl=json.load(open(db_dir+'/dscl.json'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pato/Desktop/HPV16_project/References/HPV16_16_virstrain/dscl.json'
```
But it does not seem to be an issue.

**Comment by liaoherui** [comment]
Oh, I guess you add the parameter "-m" for VirStrain.py. Try to remove that parameter and run again.

**Comment by KasperH2** [comment]
That is true, thank you. 
I have suggestion: Would you be able to add a function to determine the sitecutoff from base positions instead of a ratio? For example HPV16 is generally classified from the L1 gene region which are at position 5639 to 7156.

**Comment by liaoherui** [comment]
Hi,

Thanks for your suggestion! This function is updated, and now you can use it with the command below.

`python VirStrain_build.py -i <Input_MSA> -d <Database_Dir> -s 1 -r 5639-7156`

Any other problems, feel free to ask!

**Comment by KasperH2** [comment]
Nice!
