### ISSUE TITLE
Creating custom database duration

### ISSUE THREAD

**Issue by abulenciamiguel** [liaoherui/VirStrain#12]
Hello.

I'm trying to build a custom database of 98 SARS-CoV-2 genomes in our hpc. I would just like to ask how long does it take to build the database?

I use the pip-install VirStrain v1.12. The msa file containing the 98 genomes is about 2.8 MB and I used the following command:
virstrain_build -i refGenome/VOI_RepresentativeGenomes_CodonAligned_2022-08-15.fasta -d virstrainDB -s 1

I can see a file VirStrain_build.column that has already inflated to 11 GB and the run still continuing for two days now.

Thank you.

**Comment by liaoherui** [comment]
Hi, 
constructing the custom database for 98 SARS-CoV-2 genomes with VirStrain should be very efficient (usually several minutes). Thus, this could be a bug of VirStrain or there are some problems with the input genomes. 

In this case, Would you mind sending a sub-msa file to me to check it? For example, you can extract the msa of 10 genomes randomly from the "VOI_RepresentativeGenomes_CodonAligned_2022-08-15.fasta " file to me. Then, I can check this issue quickly. Thanks!

**Comment by liaoherui** [comment]
Hi, 
I have checked this issue. The issue can be a result of the wrong head name of the fasta file. When I replace the "|" to "/", and "." to "_" in the head name. The program works well. I have provided a re-format file for you to try. This file works fine for me.

[full_reformat.zip](https://github.com/liaoherui/VirStrain/files/11451119/full_reformat.zip)

**Comment by abulenciamiguel** [comment]
Thank you for this. This is my second time in getting an error due to header names. Sorry for this.

:D
