### ISSUE TITLE
No such file or directory: 'dengue_db/dscl.json'

### ISSUE THREAD

**Issue by Rohit-Satyam** [liaoherui/VirStrain#15]
Hi @liaoherui 

I tried running Virstrain in `--high_mutation_virus` mode however I get this warning:

```
virstrain -i SRR27845686_1.fastq -p SRR27845686_2.fastq -d dengue_db -o temp_test -m
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/virstrain/lib/python3.7/site-packages/VirStrain/S3_Strain_pred_My_Method_For_HIV.py", line 102, in <module>
    dscl=json.load(open(db_dir+'/dscl.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'dengue_db/dscl.json'
```

But if I let it run, it produces some results. Should I be worried? The results obtained are exactly the same compared to the run without the flag `-m`.

**Comment by liaoherui** [comment]
Hi, Rohit,

Usually, `--high-mutation-virus` parameter is not recommended. Because it's used to handle super divergent viral species like HIV and may has some bugs when is applied to other viruses. For Dengue virus, I think it should be fine to run the tool without -m parameter. Hope this helps.
