### ISSUE TITLE
request to add argument to print the version

### ISSUE THREAD

**Issue by Rohit-Satyam** [liaoherui/VirStrain#16]
@liaoherui I was wondering if you can add a parameter to print the version of the tool because I am not sure if I downloaded the latest version. 

Besides I keep on getting this error message while building the database:

```
Newly added sites number:  0 / 0
Kmer POS-Snp file done! Start generating matrix.
Traceback (most recent call last):
  File "bin/S2_remove_redundant_For_Me.py", line 25, in <module>
    if int(c) not in carr:
ValueError: invalid literal for int() with base 10: ''

```

Most of the files are of 0kb

```
python VirStrain_build.py --i denv.mafft.aln -d denv_virstrain_s0.6_revised -s 0.6
```

I have `15788` sequences in MSA so is it because of that?

**Comment by liaoherui** [comment]
Sorry for late reply. I am very busy these  days.

Can you check the head name of your input strains? E.g. Whether there are duplicate names or special characters? Please make sure all head name of your input strains are in the format as suggested.
![image](https://github.com/liaoherui/VirStrain/assets/22760266/e273fde2-5894-48c8-ae71-7fcb453a2627)

**Comment by liaoherui** [comment]
Hi, thanks for using VirStrain!

Currently, the -v parameter is only supported by `virstrain -v `and `virstrain_build -v`.

**Comment by Rohit-Satyam** [comment]
Even that doesn't work. Tried that too 🥹
