### ISSUE TITLE
Long-read support

### ISSUE THREAD

**Issue by Balays** [liaoherui/VirStrain#2]
Hello!
Can I use your program with long-reads (ONT MinIon, in particular) ?
Thanks!

**Comment by liaoherui** [comment]
Hi,

In theory, VirStrain can take long reads as input directly. 

However, we didn't evaluate the performance of VirStrain on long reads. The high error rate of long reads may decrease the accuracy of VirStrain. But you can try it.

Any other problems, just let me know.
