### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by niemasd** [liaoherui/VirStrain#6]
I installed VirStrain using `pip` on my Ubuntu environment in Windows Subsystem for Linux (Windows 11) as follows (this is the syntax I use to install all Python packages, and it works in the past):

```bash
sudo -H pip3 install virstrain==1.10
```

However, when I run `virstrain`, I get the following:

```bash
$ virstrain -i reads.fastq.gz -d /usr/local/bin/VirStrain_DB/SCOV2 -o tmp
python: can't open file '/usr/lib/python3/dist-packages/VirStrain/S3_Strain_pred_My_Method_V0819_Val.py': [Errno 2] No such file or directory
mv: cannot stat 'VirStrain_report.txt': No such file or directory
mv: cannot stat 'VirStrain_report.html': No such file or directory
mv: cannot stat 'Mps_ps_depth.csv': No such file or directory
mv: cannot stat 'Ops_ps_depth.csv': No such file or directory
```

I imagine that first line is the issue (and the other lines are complaining because some files that first line is supposed to create aren't getting created)

**Comment by niemasd** [comment]
I was able to get a hacky workaround by doing the following to create a symlink from the files VirStrain was expecting into the directory it was expecting them to be in:

```bash
sudo mkdir -p /usr/lib/python3/dist-packages/
sudo ln -s /usr/local/lib/python3.8/dist-packages/VirStrain /usr/lib/python3/dist-packages/VirStrain
```

However, I highly recommend against this solution, as `pip` won't remove/change those symlinks (e.g. if the user wants to uninstall, or a future update changes the folder structure, etc.)

And then even getting past that error, it now gets the following error:

```bash
$ $ virstrain -i reads.fastq.gz -d /usr/local/bin/VirStrain_DB/SCOV2 -o tmp
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported format
Aborted
Failed to open input file 'Tem_VS.jf'
No kmers matched! No virus strain can be detected!
mv: cannot stat 'VirStrain_report.txt': No such file or directory
mv: cannot stat 'VirStrain_report.html': No such file or directory
mv: cannot stat 'Mps_ps_depth.csv': No such file or directory
mv: cannot stat 'Ops_ps_depth.csv': No such file or directory
```

**Comment by niemasd** [comment]
Actually, it seems like the "unsupported format" issue was a matter of lack of support for gzipped FASTQs (which may be good to add, as I imagine most folks have gzipped FASTQs)

Though the original issue still holds

**Comment by liaoherui** [comment]
Hi, Niema, you are correct that the error is caused by the wrong format of FASTQs. Currently, VirStrain doesn't support gzipped FASTQs. And I will update VirStrain to make it support for gzipped FASTQs asap!

Thanks for your suggestions!

**Comment by liaoherui** [comment]
> 

Hi, Niema, I also test your command to install VirStrain on my own Ubuntu environment in Windows Subsystem for Linux (Windows 11). It works fine (see screenshot below). However, I'd recommend you build a **new conda environment** and then install VirStrain using pip or bioconda. In my own test, I install VirStrain by using "pip3 install virstrain==1.10" in a new conda environment and it works fine. If there are still problems, let me know please, and I will check it. Thanks!
![image](https://user-images.githubusercontent.com/22760266/152626027-1c7b961e-57a9-4323-9926-25f04803cfbb.png)


> I installed VirStrain using `pip` on my Ubuntu environment in Windows Subsystem for Linux (Windows 11) as follows (this is the syntax I use to install all Python packages, and it works in the past):
> 
> ```shell
> sudo -H pip3 install virstrain==1.10
> ```
> 
> However, when I run `virstrain`, I get the following:
> 
> ```shell
> $ virstrain -i reads.fastq.gz -d /usr/local/bin/VirStrain_DB/SCOV2 -o tmp
> python: can't open file '/usr/lib/python3/dist-packages/VirStrain/S3_Strain_pred_My_Method_V0819_Val.py': [Errno 2] No such file or directory
> mv: cannot stat 'VirStrain_report.txt': No such file or directory
> mv: cannot stat 'VirStrain_report.html': No such file or directory
> mv: cannot stat 'Mps_ps_depth.csv': No such file or directory
> mv: cannot stat 'Ops_ps_depth.csv': No such file or directory
> ```
> 
> I imagine that first line is the issue (and the other lines are complaining because some files that first line is supposed to create aren't getting created)

**Comment by liaoherui** [comment]
> Actually, it seems like the "unsupported format" issue was a matter of lack of support for gzipped FASTQs (which may be good to add, as I imagine most folks have gzipped FASTQs)
> 
> Though the original issue still holds

I have updated the script to make the tool support gzipped FASTQs. You can try the latest version in the Github repositories. For the version in pip and bioconda, I will also update the new feature asap.

**Comment by niemasd** [comment]
That's awesome! Looking forward to trying it out 😄
