### ISSUE TITLE
Vscore missing

### ISSUE THREAD

**Issue by KasperH2** [liaoherui/VirStrain#9]
Hi, 

Where is the Vscore located? I do not see this in the output.
Looking for it in the repo with grep, shows it does not exist other than in the README.md ?

Also, is it possible to sort the most possible type by matches to the sites? 
I.e I have a cased of HPV16 that looks like this:
		>AF536179_1	Cluster4_1	NA	0.9600636508109913	253/363	253/363	NA	NA
		>HPV16_K02718_1_revised	Cluster11_1	NA	0.9525978723974383	257/363	257/363	NA	NA

It is very likely that the truth is HPV16_K02718_1_revised and not AF536179_1, but the maprate is weighted higher as of now. 
I could of course look manually, but would it be possible to sort automatically as i might soon be running hundreds of samples?

Thank you

**Comment by liaoherui** [comment]
Hi, KasperH2,
In the output file, "Map_score" refers to "Vscore".
I will update a parameter as soon as possible, which can sort the most possible strain by matches to the sites.

**Comment by liaoherui** [comment]
Hi, KasperH2,
I have updated a new parameter "-s" to sort the most possible strain by matches to the sites. You can try this new function with "-s 1" in your commands. 
However, I haven't tested this parameter with suitable data. Thus, if there are any problems, let me know, please. Thanks!

**Comment by KasperH2** [comment]
With the parameter I'm getting this error:
printf: ‘3/175’: value not completely converted

**Comment by liaoherui** [comment]
This error info is a little strange... Can you type the full command you use? 

In addition, it's a little hard to debug without the reference database and input reads. If possible, can you send me a demo database and reads for debugging via email (heruiliao2-c@my.cityu.edu.hk)? Thanks!

**Comment by liaoherui** [comment]
Hi, KasperH2,
I have fixed one bug in the code, which could be the reason. Can you run with the latest version? Thanks!

**Comment by liaoherui** [comment]
Hi, KasperH2,
This problem is also fixed! Please try the latest version.

**Comment by KasperH2** [comment]
Yes, works now. Thanks!
